package com.vamsi.worldcountriesinformation.core.designsystem

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.luminance
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlin.math.max
import kotlin.math.min

/**
 * Guards the static Explorer palette against contrast regressions. Dynamic color schemes are
 * generated by Material and are not covered here.
 */
class ThemeContrastTest {

    @Test
    fun `light scheme meets WCAG AA`() = assertScheme("light", ExplorerLightColorScheme)

    @Test
    fun `dark scheme meets WCAG AA`() = assertScheme("dark", ExplorerDarkColorScheme)

    private fun assertScheme(name: String, scheme: ColorScheme) {
        val textPairs = listOf(
            "primary" to (scheme.onPrimary to scheme.primary),
            "primaryContainer" to (scheme.onPrimaryContainer to scheme.primaryContainer),
            "secondary" to (scheme.onSecondary to scheme.secondary),
            "secondaryContainer" to (scheme.onSecondaryContainer to scheme.secondaryContainer),
            "tertiary" to (scheme.onTertiary to scheme.tertiary),
            "tertiaryContainer" to (scheme.onTertiaryContainer to scheme.tertiaryContainer),
            "error" to (scheme.onError to scheme.error),
            "errorContainer" to (scheme.onErrorContainer to scheme.errorContainer),
            "surface" to (scheme.onSurface to scheme.surface),
            "surfaceVariant text" to (scheme.onSurfaceVariant to scheme.surface),
            "surfaceVariant" to (scheme.onSurfaceVariant to scheme.surfaceVariant),
            "surfaceContainerLow" to (scheme.onSurface to scheme.surfaceContainerLow),
            "surfaceContainerHigh" to (scheme.onSurface to scheme.surfaceContainerHigh),
            "surfaceContainerHighest secondary text" to (scheme.onSurfaceVariant to scheme.surfaceContainerHighest),
            "inverseSurface" to (scheme.inverseOnSurface to scheme.inverseSurface),
            "primary on surface" to (scheme.primary to scheme.surface),
            "tertiary on surface" to (scheme.tertiary to scheme.surface),
            "error on surface" to (scheme.error to scheme.surface),
        )
        textPairs.forEach { (label, pair) -> assertContrast(name, label, pair.first, pair.second, MIN_TEXT) }
        assertContrast(name, "outline on surface", scheme.outline, scheme.surface, MIN_NON_TEXT)
        assertContrast(name, "outline on surfaceContainerLow", scheme.outline, scheme.surfaceContainerLow, MIN_NON_TEXT)
    }

    private fun assertContrast(scheme: String, label: String, fg: Color, bg: Color, minimum: Double) {
        val ratio = contrast(fg, bg)
        assertTrue(
            "$scheme/$label contrast %.2f is below %.1f".format(ratio, minimum),
            ratio >= minimum,
        )
    }

    private fun contrast(a: Color, b: Color): Double {
        val la = a.luminance().toDouble() + 0.05
        val lb = b.luminance().toDouble() + 0.05
        return max(la, lb) / min(la, lb)
    }

    private companion object {
        const val MIN_TEXT = 4.5
        const val MIN_NON_TEXT = 3.0
    }
}
